- name: gathering facts
  hosts: all
  tasks:
    - name: printing facts using debug module
      debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
      
    - name: printing facts using debug module
      debug:
        msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
      
    - shell: /usr/bin/uptime
      register: result
    
    - debug:
        var: result
    #    verbosity: 2
    
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
    #   verbosity: 4